apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: labs-jackmaloney2
  description: Jack Maloney's updated test API
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: openapi
  system: jack-lab-test2
  lifecycle: experimental
  owner: dts_cft_developers
  definition: |
