apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: labs-jackmaloney2
  description: Jack Maloney's test API
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: openapi
  system: jack-lab-test2
  lifecycle: experimental
  owner: dts_cft_developers
  definition: |
    {"openapi":"3.0.1","info":{"title":"Jack's API","license":{"name":"MIT","url":"https://opensource.org/licenses/MIT"},"version":"v0.0.1"},"externalDocs":{"description":"README","url":"https://github.com/hmcts/labs-jackmaloney2"},"servers":[{"url":"http://localhost","description":"Generated server url"}],"paths":{"/testing":{"get":{"tags":["test-controller"],"summary":"Test api","description":"This is a test endpoint","operationId":"welcome","responses":{"404":{"description":"No welcome could be found","content":{"text/plain":{"schema":{"type":"string"}}}},"200":{"description":"A test message","content":{"text/plain":{"schema":{"type":"string"}}}}}}},"/":{"get":{"tags":["root-controller"],"summary":"Get welcome api","description":"This is a welcome endpoint","operationId":"welcome_1","responses":{"404":{"description":"No welcome could be found","content":{"text/plain":{"schema":{"type":"string"}}}},"200":{"description":"A welcome message","content":{"text/plain":{"schema":{"type":"string"}}}}}}}},"components":{}}
