apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-hmcts-examples-component"
  description: This is a test example of a Backstage component for HMCTS
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/backstage-hmcts-examples
    github.com/project-slug: 'hmcts/backstage-hmcts-examples'
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    backstage.io/spectral-ruleset-url: "https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/main/zalando.yml"
  tags:
    - java
  links:
    # update to match your slack channel
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: backstage-hmcts-examples
  lifecycle: experimental
  owner: dts_cft_developers
  providesApis:
    - backstage-hmcts-examples-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-hmcts-examples-api
  description: This is a test API to show examples of Backstage API entity for HMCTS
  annotations:
    github.com/project-slug: 'hmcts/backstage-hmcts-examples'
spec:
  type: openapi
  lifecycle: experimental
  owner: dts_cft_developers
  system: backstage-hmcts-examples
  apiProvidedBy: backstage-hmcts-examples-component
  definition:
    $text: https://raw.githubusercontent.com/hmcts/backstage-hmcts-examples/master/src/main/resources/openapi/testspec.yaml
