apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "jack-lab-component"
  description: This is a test from JM
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_jack-lab-test2/labs-jackmaloney2
    github.com/project-slug: 'hmcts/labs-jackmaloney2'
    backstage.io/adr-location: docs/adrs
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: jack-lab-test2
  lifecycle: experimental
  owner: dts_cft_developers
  providesApis:
    - labs-jackmaloney2

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: labs-jackmaloney-api
  description: Jack Maloney’s test API
  annotations:
    github.com/project-slug: 'hmcts/labs-jackmaloney2'
spec:
  type: openapi
  lifecycle: experimental
  owner: dts_cft_developers
  system: jack-lab-test2
  apiProvidedBy: jack-lab-component
  definition:
    $text: https://raw.githubusercontent.com/hmcts/labs-jackmaloney2/master/src/main/resources/openapi/testspec.yaml
