markdown_extensions:
  - markdown_inline_mermaid

site_name: 'Backstage HMCTS Examples'

nav:
  - Index page: index.md
  - Another section:
      - Another subpage: techdocs/example-tech-doc.md
plugins:
  - techdocs-core
