site_name: 'Backstage HMCTS Examples'

nav:
  - Index page: index.md
  - Another section:
      - Another subpage: techdocs/example-tech-doc-mermaid.md
plugins:
  - techdocs-core

markdown_extensions:
  - markdown_inline_mermaid
