apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adr
  title: Create HMCTS ADR
  description: Generate a HMCTS Architecture Decision Record and commit it to a repo
spec:
  owner: centre-of-excellence
  type: adr
  parameters:
    - title: Fill in ADR details
      required:
        - adrTitle
        - date
        - deciders
        - technicalStory
        - status
        - context
        - decision
        - pros
        - consAndRisks
        - alternativesConsidered
        - furtherConsiderations
      properties:
        adrTitle:
          type: string
          title: ADR Title
          ui:autofocus: true
        date:
          type: string
          title: Date
          ui:widget: date
          ui:options:
            format: 'yyyy-MM-dd'
            ui:help: 'Select the date the decision for the ADR was made'
        deciders:
          type: string
          title: Deciders
        technicalStory:
          type: string
          title: Technical Story / JIRA reference
        status:
          type: string
          title: Status
          enum:
            - proposed
            - accepted
            - deprecated
        context:
          type: string
          title: Context / Background
          ui:widget: textarea
          ui:
            options:
              rows: 5
        decision:
          type: string
          title: Decision
          ui:widget: textarea
          ui:
            options:
              rows: 5
        pros:
          type: string
          title: Pros
          ui:widget: textarea
          ui:
            options:
              rows: 5
        consAndRisks:
          type: string
          title: Cons and Risks
          ui:widget: textarea
          ui:
            options:
              rows: 5
        alternativesConsidered:
          type: string
          title: Alternatives Considered
          ui:widget: textarea
          ui:
            options:
              rows: 5
        furtherConsiderations:
          type: string
          title: Further Considerations
          ui:widget: textarea
          ui:
            options:
              rows: 5

    - title: Repository location
      required:
        - repoUrl
        - adrNumber
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - hmcts
              - hmcts-test
        adrNumber:
          type: string
          title: 4 digit ADR number (e.g. 0001). This will be prefixed to the ADR filename and should be one more than the previously created ADR.
  steps:
    - id: fetch-adr
      name: Fetch ADR skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./docs/adrs
        values:
          adrTitle: ${{ parameters.adrTitle }}
          date: ${{ parameters.date }}
          deciders: ${{ parameters.deciders }}
          technicalStory: ${{ parameters.technicalStory }}
          status: ${{ parameters.status }}
          context: ${{ parameters.context }}
          decision: ${{ parameters.decision }}
          pros: ${{ parameters.pros }}
          consAndRisks: ${{ parameters.consAndRisks }}
          alternativesConsidered: ${{ parameters.alternativesConsidered }}
          furtherConsiderations: ${{ parameters.furtherConsiderations }}

    - id: rename-adr
      name: Rename ADR file
      action: fs:rename
      input:
        files:
          - from: ./docs/adrs/adr_template.md
            to: './docs/adrs/${{ parameters.adrNumber }}-${{ parameters.adrTitle | replace(" ", "-") | lower}}.md'

    - id: publish
      name: Publish ADR via GitHub
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: 'adr-${{ parameters.adrTitle | replace(" ", "_")  | lower }}'
        title: 'Add ADR: ${{ parameters.adrTitle }}'
        description: 'This PR adds a new ADR created via the Backstage template.'
