apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adr
  title: Create HMCTS ADR 5
  description: Generate a HMCTS Architecture Decision Record and commit it to a repo
spec:
  owner: centre-of-excellence
  type: adr
  parameters:
    - title: Fill in ADR details
      required:
        - adrTitle
        - status
        - context
        - decision
        - consequences
      properties:
        adrTitle:
          type: string
          title: ADR Title
          ui:autofocus: true
        status:
          type: string
          title: Status
          enum:
            - proposed
            - accepted
            - deprecated
        context:
          type: string
          title: Context / Background
          ui:
            options:
              rows: 5
        decision:
          type: string
          title: Decision
          ui:
            options:
              rows: 5
        consequences:
          type: string
          title: Consequences
          ui:
            options:
              rows: 5

    - title: Repository location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - hmcts
              - hmcts-test
  steps:
    - id: debug-parameters
      name: Log Parameters
      action: debug:log
      input:
        message: |
          adrTitle: ${{ parameters.adrTitle }}
          status: ${{ parameters.status }}
          context: ${{ parameters.context }}
          decision: ${{ parameters.decision }}
          consequences: ${{ parameters.consequences }}
          repoUrl: ${{ parameters.repoUrl }}

    - id: fetch-adr
      name: Fetch ADR skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./adr
        values:
          adrTitle: ${{ parameters.adrTitle }}
          status: ${{ parameters.status }}
          context: ${{ parameters.context }}
          decision: ${{ parameters.decision }}
          consequences: ${{ parameters.consequences }}
          # optionally add a date
          date: ${{ parameters.date | default("") }}

    - id: publish
      name: Publish ADR via GitHub
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: 'adr-${{ parameters.adrTitle }}'
        title: 'Add ADR: ${{ parameters.adrTitle }}'
        description: 'This PR adds a new ADR created via the Backstage template.'
