name: Publish Swagger Specs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Swagger Publisher
        run: ./gradlew integration --tests uk.gov.hmcts.reform.config.SwaggerPublisherTest
      - name: Run Backstage API gen
        run: |
          echo (EOF
          apiVersion: backstage.io/v1alpha1
          kind: API
          metadata:
            name: labs-jackmaloney2
            description: Jack Maloney's test API
            links:
              - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
                title: cloud-native on Slack
                icon: chat
          spec:
            type: openapi
            system: jack-lab-test2
            lifecycle: experimental
            owner: dts_cft_developers
            definition: |
          EOF) > /tmp/labs-jackmaloney2-api.yaml
          echo "$(cat /tmp/swagger-specs.json)" >> /tmp/labs-jackmaloney2-api.yaml 
      - name: Commit to repository
        run: |
          mkdir swagger-staging
          cd swagger-staging
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub action"
          git remote add upstream "https://jenkins-reform-hmcts:${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}@github.com/hmcts/reform-api-docs.git"
          git pull upstream master
          repo=`echo "$GITHUB_REPOSITORY" | cut -f2- -d/`
          echo "$(cat /tmp/swagger-specs.json)" > "docs/specs/send-letter-service.json"
          echo "$(cat /tmp/labs-jackmaloney2-api.yaml)" > "docs/backstage/labs-jackmaloney2-api.yaml"
          git add "docs/specs/send-letter-service.json"
          git add "docs/backstage/labs-jackmaloney2-api.yaml"
          # Only commit and push if we have changes.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update spec and api.yaml for $repo#${GITHUB_SHA:7}"; git push --set-upstream upstream master)
